-- MySQL Script generated by MySQL Workbench
-- sex 28 mai 2021 23:06:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurantedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurantedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurantedb` ;
USE `restaurantedb` ;

-- -----------------------------------------------------
-- Table `restaurantedb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantedb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(90) NOT NULL,
  `dthrcriacao` DATETIME NOT NULL,
  `dthralteracao` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
