-- MySQL Script generated by MySQL Workbench
-- ter 01 jun 2021 22:19:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurantedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurantedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurantedb` ;
USE `restaurantedb` ;

-- -----------------------------------------------------
-- Table `restaurantedb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantedb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(90) NOT NULL,
  `dthrcriacao` DATETIME NOT NULL,
  `dthralteracao` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurantedb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantedb`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `tamanho` VARCHAR(45) NULL,
  `dthrcriacao` DATETIME NOT NULL,
  `dthralteracao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurantedb`.`preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantedb`.`preco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preco` DECIMAL(10,2) NOT NULL,
  `dthrcriacao` DATETIME NOT NULL,
  `id_produto` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_produto_UNIQUE` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `restaurantedb`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
