-- MySQL Script generated by MySQL Workbench
-- seg 28 jun 2021 11:17:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema creditcarddb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `creditcarddb` ;

-- -----------------------------------------------------
-- Schema creditcarddb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `creditcarddb` ;
USE `creditcarddb` ;

-- -----------------------------------------------------
-- Table `creditcarddb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcarddb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(90) NOT NULL,
  `dthrcriacao` DATETIME NOT NULL,
  `dthralteracao` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcarddb`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcarddb`.`cartao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_cartao` VARCHAR(19) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valor_credito_disp` DECIMAL(10,2) NOT NULL,
  `cartao_bloqueado` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ccardnumber_UNIQUE` (`numero_cartao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcarddb`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcarddb`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_cartao` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `dthrcompra` DATETIME NOT NULL,
  `aprovada` TINYINT(1) NULL DEFAULT 0,
  `estornada` TINYINT(1) NULL DEFAULT 0,
  `paga` TINYINT(1) NULL DEFAULT 0,
  `uuidcompra` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_cartao_idx` (`id_cartao` ASC) VISIBLE,
  INDEX `fk_id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `uuidcompra_UNIQUE` (`uuidcompra` ASC) VISIBLE,
  CONSTRAINT `fk_id_cartao`
    FOREIGN KEY (`id_cartao`)
    REFERENCES `creditcarddb`.`cartao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `creditcarddb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
